version: '3.7'

services:
  # Blue Environment (Default/Primary)
  converxa-backend-blue:
    container_name: converxa-backend-blue
    image: converxa-backend:blue
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      - DEPLOYMENT_COLOR=blue
    ports:
      - '3002:3001'
    networks:
      - converxa_network
    volumes:
      - ./uploads:/app/uploads
      - ./logs/blue:/app/logs
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--spider', 'http://127.0.0.1:3001/api/health']
      interval: 10s
      timeout: 10s
      retries: 4
      start_period: 3s

  # Green Environment (Secondary/Staging)
  converxa-backend-green:
    container_name: converxa-backend-green
    image: converxa-backend:green
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      - DEPLOYMENT_COLOR=green
    ports:
      - '3003:3001'
    networks:
      - converxa_network
    volumes:
      - ./uploads:/app/uploads
      - ./logs/green:/app/logs
    profiles:
      - green
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--spider', 'http://127.0.0.1:3001/api/health']
      interval: 10s
      timeout: 10s
      retries: 4
      start_period: 3s

networks:
  converxa_network:
    driver: bridge
