version: '3.7'

services:
  # Blue Environment (Default/Primary)
  sofia-chat-backend-blue:
    container_name: sofia-chat-backend-blue
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      - DEPLOYMENT_COLOR=blue
    ports:
      - '3001:3001'
    networks:
      - sofia_chat_network
    volumes:
      - ./uploads:/app/uploads
      - ./logs/blue:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Green Environment (Secondary/Staging)
  sofia-chat-backend-green:
    container_name: sofia-chat-backend-green
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      - DEPLOYMENT_COLOR=green
    ports:
      - '3002:3001'
    networks:
      - sofia_chat_network
    volumes:
      - ./uploads:/app/uploads
      - ./logs/green:/app/logs
    profiles:
      - green
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Legacy service name for backward compatibility
  sofia-chat-backend-v2:
    container_name: sofia-chat-backend-v2
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - '3001:3001'
    networks:
      - sofia_chat_network
    volumes:
      - ./uploads:/app/uploads
    profiles:
      - legacy

networks:
  sofia_chat_network:
    driver: bridge