export enum AnalyticType {
  TOTAL_USERS = 'TOTAL_USERS',
  NEW_USERS = 'NEW_USERS',

  MESSAGES_BY_WHATSAPP = 'MESSAGES_BY_WHATSAPP',
  MESSAGES_BY_FACEBOOK = 'MESSAGES_BY_FACEBOOK',
  MESSAGES_BY_WEB = 'MESSAGES_BY_WEB',
  RECURRING_USERS = 'RECURRING_USERS',
  TOTAL_MESSAGES = 'TOTAL_MESSAGES',
  IA_MESSAGES = 'IA_MESSAGES',
  HITL_MESSAGES = 'HITL_MESSAGES',
  AVG_IA_MESSAGES_PER_SESSION = 'AVG_IA_MESSAGES_PER_SESSION',
  AVG_HITL_MESSAGES_PER_SESSION = 'AVG_HITL_MESSAGES_PER_SESSION',
  AVG_SESSIONS_PER_USER = 'AVG_SESSIONS_PER_USER',
  FUNCTIONS_PER_SESSION = 'FUNCTIONS_PER_SESSION',
  SESSIONS = 'SESSIONS',
  FUNCTION_CALLS = 'FUNCTION_CALLS',
}

export enum StatisticsDisplayType {
  PIE = 'PIE',
  BAR = 'BAR',
  AREA = 'AREA',
  METRIC = 'METRIC',
}

export enum TimeRange {
  LAST_DAY = '1d', // Último día
  LAST_7_DAYS = '7d', // Últimos 7 días
  LAST_30_DAYS = '30d', // Últimos 30 días
  LAST_90_DAYS = '90d', // Últimos 90 días
  LAST_6_MONTHS = '180d', // Últimos 6 meses
  LAST_YEAR = '365d',
}
