name: Blue-Green Production Deployment for Converxa Chat Backend

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'scripts/**'
      - 'src/**'
      - 'Dockerfile'
      - 'docker-compose*.yml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Blue-Green action to perform'
        required: true
        type: choice
        options:
          - deploy
          - switch
          - rollback
          - status
        default: 'deploy'

env:
  DEPLOY_HOST: 137.184.44.230
  DEPLOY_USER: root
  SSH_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
  PROJECT_PATH: /root/repos/converxa-backend-v1

jobs:
  blue-green-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update repository and environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.PROJECT_PATH }}

            echo "=== ESTADO INICIAL DEL REPOSITORIO ==="
            echo "Commit actual: $(git rev-parse --short HEAD)"
            echo "Branch actual: $(git branch --show-current)"
            git status --short

            # Pull latest changes and ensure working files are synchronized
            echo "=== ACTUALIZANDO REPOSITORIO ==="
            git fetch origin
            git checkout main
            git pull origin main
            git reset --hard HEAD

            echo "=== ESTADO DESPUÉS DE LA ACTUALIZACIÓN ==="
            echo "Commit final: $(git rev-parse --short HEAD)"
            echo "Último commit: $(git log --oneline -1)"
            git status --short

            # Create environment file with proper quoting
            cat > .env << 'ENV_EOF'
            NODE_ENV=production
            LOG_LEVEL=production
            TYPEORM_HOST=converxa-prod-db-do-user-23433311-0.k.db.ondigitalocean.com
            TYPEORM_PORT=25060
            TYPEORM_USERNAME=doadmin
            TYPEORM_PASSWORD=${{ secrets.PROD_TYPEORM_PASSWORD }}
            TYPEORM_DB_NAME=defaultdb
            TYPEORM_SSL=true
            JWT_SECRET_KEY=${{ secrets.PROD_JWT_SECRET_KEY }}
            JWT_SECRET_KEY_REFRESH=${{ secrets.PROD_JWT_SECRET_KEY_REFRESH }}
            NODEMAILER_HOST=smtp.gmail.com
            NODEMAILER_PORT=587
            NODEMAILER_USER=${{ secrets.PROD_NODEMAILER_USER }}
            NODEMAILER_PASS=${{ secrets.PROD_NODEMAILER_PASS }}
            NODEMAILER_FROM=noreply@converxa.net
            URL_FILES=https://back-chat.converxa.net
            URL_WSS=wss://back-chat.converxa.net/api/socket/web-chat
            URL_WEBHOOK_WA=https://back-chat.converxa.net/webhook/whatsapp
            OPENAI_API_KEY=${{ secrets.PROD_OPENAI_API_KEY }}
            FACEBOOK_APP_ID=your-facebook-app-id
            FACEBOOK_APP_SECRET=${{ secrets.PROD_FACEBOOK_APP_SECRET }}
            FACEBOOK_WEBHOOK_SECRET=${{ secrets.PROD_FACEBOOK_WEBHOOK_SECRET }}
            FACEBOOK_GRAPH_API=https://graph.facebook.com/v18.0
            APP_URL=https://back-chat.converxa.net
            URL_FRONTEND=https://app-chat.converxa.net
            MAILGUN_API_KEY=${{ secrets.PROD_MAILGUN_API_KEY }}
            MAILGUN_DOMAIN=converxa.net
            MAILGUN_FROM=noreply@converxa.net
            SLACK_CLIENT_ID=your-slack-client-id
            SLACK_CLIENT_SECRET=your-slack-client-secret
            SLACK_REDIRECT_URI=https://back-chat.converxa.net/auth/slack/callback
            VOYAGE_API_KEY=${{ secrets.PROD_VOYAGE_API_KEY }}
            CLAUDE_API_KEY=${{ secrets.PROD_CLAUDE_API_KEY }}
            GOOGLE_CLIENT_ID=your-google-client-id
            GOOGLE_CLIENT_SECRET=your-google-client-secret
            CUSTOM_PLAN_REQUEST_RECIPIENT_EMAIL=admin@converxa.net
            SOCIAL_LINK_X=https://x.com/converxa_ia
            SOCIAL_LINK_LINKEDIN=https://www.linkedin.com/company/converxa-ia/
            SOCIAL_LINK_INSTAGRAM=https://www.instagram.com/converxa-ia/
            SOCIAL_LINK_FACEBOOK=https://www.facebook.com/converxa-ia
            ENV_EOF

      - name: Execute Blue-Green Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.PROJECT_PATH }}

            # Set production environment
            export NODE_ENV=production

            # Determine action
            ACTION="${{ github.event.inputs.action || 'deploy' }}"

            echo "=== INFORMACIÓN DE DEPLOY ==="
            echo "Entorno: $NODE_ENV"
            echo "Acción: $ACTION"
            echo "Commit a deployar: $(git rev-parse --short HEAD)"
            echo "Timestamp: $(date)"
            echo "Directorio del proyecto: ${{ env.PROJECT_PATH }}"
            echo "Script a ejecutar: /opt/converxa-chat/blue-green-simple.sh"

            # Verificar que el script existe
            if [[ ! -f "/opt/converxa-chat/blue-green-simple.sh" ]]; then
                echo "ERROR: Script no encontrado en /opt/converxa-chat/blue-green-simple.sh"
                ls -la /opt/converxa-chat/
                exit 1
            fi

            echo "=== EJECUTANDO BLUE-GREEN ACTION ==="
            echo "Ejecutando acción Blue-Green: $ACTION"

            # Execute the blue-green script
            /opt/converxa-chat/blue-green-simple.sh $ACTION

            echo "=== VERIFICACIÓN POST-DEPLOY ==="
            echo "Verificando estado de contenedores después del deploy:"
            docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'

            echo "Verificando commits en contenedores:"
            echo "BLUE: $(docker exec converxa-backend-blue cat /app/.git/refs/heads/main 2>/dev/null | cut -c1-7 || echo 'N/A')"
            echo "GREEN: $(docker exec converxa-backend-green cat /app/.git/refs/heads/main 2>/dev/null | cut -c1-7 || echo 'N/A')"

      - name: Show deployment summary
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            echo "=================================="
            echo "   BLUE-GREEN PRODUCTION SUMMARY"
            echo "=================================="
            echo "Acción ejecutada: ${{ github.event.inputs.action || 'deploy' }}"
            echo "Commit deployado: $(cd ${{ env.PROJECT_PATH }} && git rev-parse --short HEAD)"
            echo "Commit completo: $(cd ${{ env.PROJECT_PATH }} && git rev-parse HEAD)"
            echo "Mensaje del commit: $(cd ${{ env.PROJECT_PATH }} && git log --format=%B -n 1 HEAD | head -1)"
            echo "Timestamp: $(date)"
            echo "=================================="

            echo "=== COMMITS EN CONTENEDORES ==="
            echo "BLUE container commit: $(docker exec converxa-backend-blue cat /app/.git/refs/heads/main 2>/dev/null | cut -c1-7 || echo 'Container not running')"
            echo "GREEN container commit: $(docker exec converxa-backend-green cat /app/.git/refs/heads/main 2>/dev/null | cut -c1-7 || echo 'Container not running')"
            echo "Repository commit: $(cd ${{ env.PROJECT_PATH }} && git rev-parse --short HEAD)"
            echo ""

            # Show current status
            /opt/converxa-chat/blue-green-simple.sh status

            echo ""
            echo "=== VERIFICACIÓN DE SALUD ==="
            echo "Verificando endpoints básicos:"

            echo -n "BLUE (3002): "
            if curl -sf http://localhost:3002/api/health >/dev/null 2>&1; then
                echo "✅ SALUDABLE"
            else
                echo "❌ NO SALUDABLE"
            fi

            echo -n "GREEN (3003): "
            if curl -sf http://localhost:3003/api/health >/dev/null 2>&1; then
                echo "✅ SALUDABLE"
            else
                echo "❌ NO SALUDABLE"
            fi

            echo -n "Producción: "
            if curl -sf https://back-chat.converxa.net/api/health >/dev/null 2>&1; then
                echo "✅ SALUDABLE"
            else
                echo "❌ NO SALUDABLE"
            fi

            echo ""
            echo "🔧 Comandos disponibles:"
            echo "  - Ver estado: /opt/converxa-chat/blue-green-simple.sh status"
            echo "  - Hacer switch: /opt/converxa-chat/blue-green-simple.sh switch"
            echo "  - Rollback: /opt/converxa-chat/blue-green-simple.sh rollback"
            echo "  - Limpiar: /opt/converxa-chat/blue-green-simple.sh cleanup"

  notify-result:
    needs: blue-green-production
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Notify deployment result
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            if [ "${{ needs.blue-green-production.result }}" = "success" ]; then
              echo "✅ Blue-Green production deployment completado exitosamente"
              echo "📋 Ejecuta '/opt/converxa-chat/blue-green-simple.sh status' para ver el estado actual"
            else
              echo "❌ Error en Blue-Green production deployment"
              echo "🔍 Revisar logs para más detalles"
              echo "📋 Estado actual:"
              /opt/converxa-chat/blue-green-simple.sh status || echo "No se pudo obtener el estado"
            fi
